[package]
name = "pisi-iso-creator"
version = "0.1.0"
edition = "2024"

[dependencies]
lzma-rs = "0.3.0"
quick-xml = "0.42.0"
serde = { version = "1.0.229", features = ["derive"] }
slint = "1.18"
toml = "1.1.7"
ureq = { version = "3.4.2", features = ["platform-verifier"] }

[build-dependencies]
slint-build = "1.18"

[dev-dependencies]
tempfile = "3.27.0"
